//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authink.Web.App_LocalResources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string ChildAdd_FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("ChildAdd_FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string ChildAdd_LastNamePlaceholder {
            get {
                return ResourceManager.GetString("ChildAdd_LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ChildAdd_Save {
            get {
                return ResourceManager.GetString("ChildAdd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child information.
        /// </summary>
        public static string ChildAdd_Title {
            get {
                return ResourceManager.GetString("ChildAdd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string ChildEdit_FirstName {
            get {
                return ResourceManager.GetString("ChildEdit_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string ChildEdit_LastName {
            get {
                return ResourceManager.GetString("ChildEdit_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ChildEdit_Save {
            get {
                return ResourceManager.GetString("ChildEdit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child info edit.
        /// </summary>
        public static string ChildEdit_Title {
            get {
                return ResourceManager.GetString("ChildEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new child.
        /// </summary>
        public static string ChildMenu_CreateNew {
            get {
                return ResourceManager.GetString("ChildMenu_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string ChildMenu_Edit {
            get {
                return ResourceManager.GetString("ChildMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConfirmationDialog_Cancel {
            get {
                return ResourceManager.GetString("ConfirmationDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct colors.
        /// </summary>
        public static string EditTaskPicturesList_CorrectColors {
            get {
                return ResourceManager.GetString("EditTaskPicturesList_CorrectColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct picture.
        /// </summary>
        public static string EditTaskPicturesList_CorrectPicture {
            get {
                return ResourceManager.GetString("EditTaskPicturesList_CorrectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string EditTaskPicturesList_Pictures {
            get {
                return ResourceManager.GetString("EditTaskPicturesList_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new picture.
        /// </summary>
        public static string EditTaskPicturesList_UploadNewPicture {
            get {
                return ResourceManager.GetString("EditTaskPicturesList_UploadNewPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong colors.
        /// </summary>
        public static string EditTaskPicturesList_WrongColors {
            get {
                return ResourceManager.GetString("EditTaskPicturesList_WrongColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong pictures.
        /// </summary>
        public static string EditTaskPicturesList_WrongPictures {
            get {
                return ResourceManager.GetString("EditTaskPicturesList_WrongPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string Omnibar_Language_Croatian {
            get {
                return ResourceManager.GetString("Omnibar_Language_Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Omnibar_Language_English {
            get {
                return ResourceManager.GetString("Omnibar_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Omnibar_Logout {
            get {
                return ResourceManager.GetString("Omnibar_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        public static string TaskConfirmationDialog_Text {
            get {
                return ResourceManager.GetString("TaskConfirmationDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TaskEdit_Description {
            get {
                return ResourceManager.GetString("TaskEdit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TaskEdit_Name {
            get {
                return ResourceManager.GetString("TaskEdit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TaskEdit_Save {
            get {
                return ResourceManager.GetString("TaskEdit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TaskPicturesEditor_Back {
            get {
                return ResourceManager.GetString("TaskPicturesEditor_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct colors.
        /// </summary>
        public static string TaskPicturesEditor_CorrectColor {
            get {
                return ResourceManager.GetString("TaskPicturesEditor_CorrectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TaskPicturesEditor_Save {
            get {
                return ResourceManager.GetString("TaskPicturesEditor_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new picture.
        /// </summary>
        public static string TaskPicturesEditor_Title {
            get {
                return ResourceManager.GetString("TaskPicturesEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong colors.
        /// </summary>
        public static string TaskPicturesEditor_WrongColor {
            get {
                return ResourceManager.GetString("TaskPicturesEditor_WrongColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit task.
        /// </summary>
        public static string TaskPreview_Edit {
            get {
                return ResourceManager.GetString("TaskPreview_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string TaskPreview_Pictures {
            get {
                return ResourceManager.GetString("TaskPreview_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed description of new test.
        /// </summary>
        public static string TestAdd_LongDescPlaceholder {
            get {
                return ResourceManager.GetString("TestAdd_LongDescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TestAdd_Save {
            get {
                return ResourceManager.GetString("TestAdd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description of new test.
        /// </summary>
        public static string TestAdd_ShortDescPlaceholder {
            get {
                return ResourceManager.GetString("TestAdd_ShortDescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new test to.
        /// </summary>
        public static string TestAdd_Title {
            get {
                return ResourceManager.GetString("TestAdd_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of new test.
        /// </summary>
        public static string TestAdd_TitlePlaceholder {
            get {
                return ResourceManager.GetString("TestAdd_TitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this test?.
        /// </summary>
        public static string TestConfirmationDialog_Text {
            get {
                return ResourceManager.GetString("TestConfirmationDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TestEdit_Delete {
            get {
                return ResourceManager.GetString("TestEdit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long description.
        /// </summary>
        public static string TestEdit_LongDescription {
            get {
                return ResourceManager.GetString("TestEdit_LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TestEdit_Name {
            get {
                return ResourceManager.GetString("TestEdit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TestEdit_Save {
            get {
                return ResourceManager.GetString("TestEdit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description.
        /// </summary>
        public static string TestEdit_ShortDescription {
            get {
                return ResourceManager.GetString("TestEdit_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new test.
        /// </summary>
        public static string TestList_CreateNew {
            get {
                return ResourceManager.GetString("TestList_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search all tests.
        /// </summary>
        public static string TestList_SearchPlaceholder {
            get {
                return ResourceManager.GetString("TestList_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string TestList_Title {
            get {
                return ResourceManager.GetString("TestList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit test.
        /// </summary>
        public static string TestPreview_EditButton {
            get {
                return ResourceManager.GetString("TestPreview_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        public static string TestTaskList_AddNew {
            get {
                return ResourceManager.GetString("TestTaskList_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TestTaskList_Delete {
            get {
                return ResourceManager.GetString("TestTaskList_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string TestTaskList_Difficulty {
            get {
                return ResourceManager.GetString("TestTaskList_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TestTaskList_Edit {
            get {
                return ResourceManager.GetString("TestTaskList_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TestTaskList_Title {
            get {
                return ResourceManager.GetString("TestTaskList_Title", resourceCulture);
            }
        }
    }
}
