//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskWizard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskWizard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authink.Web.App_LocalResources.TaskWizard", typeof(TaskWizard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string ChooseDifficulty_Difficulty {
            get {
                return ResourceManager.GetString("ChooseDifficulty_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose difficulty.
        /// </summary>
        public static string ChooseDifficulty_Title {
            get {
                return ResourceManager.GetString("ChooseDifficulty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type.
        /// </summary>
        public static string ChooseType_Title {
            get {
                return ResourceManager.GetString("ChooseType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string InputMetaData_Task_Description {
            get {
                return ResourceManager.GetString("InputMetaData_Task_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string InputMetaData_Task_Title {
            get {
                return ResourceManager.GetString("InputMetaData_Task_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic task information.
        /// </summary>
        public static string InputMetaData_Title {
            get {
                return ResourceManager.GetString("InputMetaData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string InputMetaData_VoiceCommand_Optional {
            get {
                return ResourceManager.GetString("InputMetaData_VoiceCommand_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string InputMetaData_VoiceCommand_Required {
            get {
                return ResourceManager.GetString("InputMetaData_VoiceCommand_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice command.
        /// </summary>
        public static string InputMetaData_VoiceCommand_Title {
            get {
                return ResourceManager.GetString("InputMetaData_VoiceCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Omnibar_Cancel {
            get {
                return ResourceManager.GetString("Omnibar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Omnibar_Step {
            get {
                return ResourceManager.GetString("Omnibar_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct color.
        /// </summary>
        public static string UploadPictures_Colors_CorrectColor {
            get {
                return ResourceManager.GetString("UploadPictures_Colors_CorrectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong colors.
        /// </summary>
        public static string UploadPictures_Colors_IncorrectColors {
            get {
                return ResourceManager.GetString("UploadPictures_Colors_IncorrectColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For every picture you upload, you have to choose a correct and an incorrect color..
        /// </summary>
        public static string UploadPictures_Colors_Info {
            get {
                return ResourceManager.GetString("UploadPictures_Colors_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the correct picture..
        /// </summary>
        public static string UploadPictures_DetectItem_Info {
            get {
                return ResourceManager.GetString("UploadPictures_DetectItem_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadPictures_DetectItem_UploadWrong_1 {
            get {
                return ResourceManager.GetString("UploadPictures_DetectItem_UploadWrong_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect pictures..
        /// </summary>
        public static string UploadPictures_DetectItem_UploadWrong_2 {
            get {
                return ResourceManager.GetString("UploadPictures_DetectItem_UploadWrong_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to upload a picture..
        /// </summary>
        public static string UploadPictures_OrderBySize_Info {
            get {
                return ResourceManager.GetString("UploadPictures_OrderBySize_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to upload.
        /// </summary>
        public static string UploadPictures_Simple_UploadText_1 {
            get {
                return ResourceManager.GetString("UploadPictures_Simple_UploadText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pictures..
        /// </summary>
        public static string UploadPictures_Simple_UploadText_2 {
            get {
                return ResourceManager.GetString("UploadPictures_Simple_UploadText_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload pictures.
        /// </summary>
        public static string UploadPictures_Title {
            get {
                return ResourceManager.GetString("UploadPictures_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadPictures_Upload {
            get {
                return ResourceManager.GetString("UploadPictures_Upload", resourceCulture);
            }
        }
    }
}
