//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authink.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public Child()
        {
            this.Tests = new HashSet<Test>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DateOfBirth { get; set; }
        public string Notes { get; set; }
        public string Center { get; set; }
        public string Contact { get; set; }
        public string DescriptionOfCondition { get; set; }
        public string PlaceOfBirth { get; set; }
        public string ParentName { get; set; }
        public bool IsHidden { get; set; }
        public string ProfilePictureUrl { get; set; }
    
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
