//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authink.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetToken
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<System.DateTime> UsedOn { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
