//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authink.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.Colors = new HashSet<Color>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public bool IsHidden { get; set; }
        public string Theme { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
    
        public virtual ICollection<Color> Colors { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Sound Sound { get; set; }
    }
}
