//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authink.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics_Meta
    {
        public Statistics_Meta()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string SucessfullClicks { get; set; }
        public string ErrorClicks { get; set; }
        public string TotalRunSummary { get; set; }
        public string Dates { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
