//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authink.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Tasks = new HashSet<Task>();
            this.Children = new HashSet<Child>();
            this.Tests = new HashSet<Test>();
            this.PasswordResetTokens = new HashSet<PasswordResetToken>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Child> Children { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<PasswordResetToken> PasswordResetTokens { get; set; }
    }
}
